name: coffeencode
favicon: null
layout_spectrum: 0.5026412887964398
typography_spectrum: 0.7844393206760287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8c8c8'
    - '#707070'
    - '#190600'
    - '#4e4e4e'
  brandStrength: 0.1875
  lightness: 0.9040487913880497
  saturation: 0.5313135320320725
  rhythmicContrast: 0.8986183172091842
purpose: []
