typography_spectrum: 0.7844393206760287
color:
  brandColors:
    - '#ffffff'
    - '#c8c8c8'
    - '#707070'
    - '#190600'
    - '#4e4e4e'
  brandStrength: 0.1875
  lightness: 0.9040487913880497
  saturation: 0.5313135320320725
  rhythmicContrast: 0.8986183172091842
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5026412887964398
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f644889-a61b-45e0-81dc-bbce6fb50a4c.png
name: coffeencode
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eebae800-bdc4-4c94-a92e-e0044f1f1d39.png
title: 'We like Coffee, we like to build stuff'
description: our AI builds stuff with us
purpose: []
